<?php

/**
 * Module that plugs in Sirportly functionality to your Drupal web site.
 * For Sirportly information see: http://sirportly.com
 */

include_once('libs/class.php');
include_once('libs/markdown.php');

define('SIRPORTLY_API_URL', 'https://api.sirportly.com/');

/**
 * Implementation of hook_init()
 */
function sirportly_init() {

  if (variable_get('sp_enable_styling', NULL)) {
    drupal_add_css(drupal_get_path('module', 'sirportly') . '/sirportly.default.css');
  }

}

/**
 * Implementation of hook_menu()
 */
function sirportly_menu() {

    $items['admin/config/services/sirportly'] = array(
      'title' => 'Sirportly API Settings',
      'description' => 'Connects to the Sirportly API',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('sirportly_admin'),
      'access arguments' => array('administer sirportly'),
      'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/sirportly'] = array(
      'title' => 'Support',
      'access arguments' => array('submit sirportly ticket'),
      'page callback' => 'sirportly_home',
      'type' => MENU_NORMAL_ITEM
    );

    $items['admin/sirportly/submit'] = array(
      'title' => 'Submit a support ticket',
      'description' => 'Submit a support ticket directly to {{ company_name }} from here.',
      'page callback' => 'sirportly_ticket_submit',
      'access arguments' => array('submit sirportly ticket'),
      'type' => MENU_LOCAL_ACTION,
    );

    $items['admin/sirportly/view/%'] = array(
      'title' => 'Support Ticket',
      'description' => 'Submit a support ticket directly to {{ company_name }} from here.',
      'page callback' => 'sirportly_ticket_view',
      'page arguments' => array(3),
      'access arguments' => array('submit sirportly ticket'),
      'type' => MENU_CALLBACK,
    );

    $items['admin/sirportly/knowledge/view/%'] = array(
      'title' => 'Knowledgebase',
      'description' => 'Submit a support ticket directly to {{ company_name }} from here.',
      'page callback' => 'sirportly_kb_view',
      'page arguments' => array(4),
      'access arguments' => array('submit sirportly ticket'),
      'type' => MENU_CALLBACK,
    );

    return $items;
}

function sirportly_ticket_view($ticket_id) {

  $token = variable_get('sirportly_api_token', '');

  $secret = variable_get('sirportly_api_secret', '');

  $s = new Sirportly($token, $secret);

  $ticket = $s->ticket($ticket_id);

  drupal_set_title($ticket['subject']);

  // dump($ticket);

return theme('view_ticket', array(
    'date' => strtotime($ticket['submitted_at']),
    'subject' => $ticket['subject'],
    'message' => $ticket['updates'][0]['message'],
    'customer' => $ticket['customer'],
    'email' => $ticket['customer_contact_method']['method_type'] == 'email' ? $ticket['customer_contact_method']['data'] : NULL,
    )
  );



}

function sirportly_home() {

  $token = variable_get('sirportly_api_token', '');

  $secret = variable_get('sirportly_api_secret', '');

  global $user;

  $sirportly_ids = variable_get("Sirportly_ID_list_{$user->uid}", array());

  if (!$sirportly_ids || count($sirportly_ids) === 0) {
    return 'You have not submitted any tickets to us yet.';
  }

  $s = new Sirportly($token, $secret);

  $tickets = array();

  foreach ($sirportly_ids as $sid) {

    $users = $s->query('/api/v1/tickets/customer', array('customer' => $sid));

    foreach ($users['records'] as $t) {
      if ($t['status_type'] == 0) {
        $tickets[] = $t;
      }

    }

  }

  // Process the tickets.

  $headers = array(
    t('Subject'),
    t('Date Submitted'),
    t('View'),
  );

  $rows = array();

  // Sort the tickets
  usort($tickets, function($a, $b) {

    $timea = strtotime($a['submitted_at']);
    $timeb = strtotime($b['submitted_at']);

    if ($timea < $timeb) {
      return 1;
    }
    elseif ($timea > $timeb) {
      return -1;
    }
    else {
      return 0;
    }

  });

  foreach ($tickets as $ticket) {

    $rows[] = array(
      $ticket['subject'],
      date("jS F Y, H:ia", strtotime($ticket['submitted_at'])),
      l('View', 'admin/sirportly/view/' . $ticket['reference']),
    );

  }

  if (count($tickets) > 0) {
    $ticket_table = theme_table(array(
      'header' => $headers,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => '',
      'colgroups' => array(),
      'sticky' => FALSE,
      'empty' => TRUE,
      'attributes' => array(
        'id' => 'sirportly-tickets'
      )
    ));
  }
  else {
    $ticket_table = '<p class="no-results-tickets">No Tickets To Show</p>';
  }

  $kbs = variable_get('sp_active_knowledgebase', array());

  foreach ($kbs as $key => $kbid) {
   $kbs[$key] = explode(":", $kbid);
  }

  return theme('sp_support_page', array('ticket_table' => $ticket_table, 'knowledge_bases' => $kbs));

}

/**
 * Implementation of hook_permission
 */
function sirportly_permission() {
  return array(
    'administer sirportly' => array(
      'title' => t('Administer Sirtportly')
    ),
    'submit sirportly ticket' => array(
      'title' => t('Submit support tickets using the Sirportly module'),
    ),
  );
}

/**
 * Implementation of hook_theme()
 */
function sirportly_theme() {
  return array(
    'view_ticket' => array(
      'template' => 'view-ticket',
      'variables' => array('message' => NULL, 'subject' => NULL, 'meta' => NULL, 'date' => NULL)
    ),
    'sp_support_page' => array(
      'template' => 'sp-support-page',
      'vars' => array(
        'tickets' => NULL,
        'knowledge_bases' => NULL,
      ),
    ),
    'knowledgebase_page' => array(
      'template' => 'sp-kb-page',
      'vars' => array(
        'menu' => NULL,
        'content' => NULL,
      )
    ),
  );
}

// Create the form
function sirportly_admin() {

  // Check that the needed metadata is there, and if not, download it and store it.

  cache_sirportly_metadata();

  $form = array();

  $collapsed = is_string(variable_get('sirportly_api_token', NULL)) && is_string(variable_get('sirportly_api_secret', NULL)) ? TRUE : FALSE;

  $form['sirportly_account'] = array(
    '#type' => 'fieldset',
    '#title' => t('Sirportly API credentials'),
    '#collapsible' => TRUE,
    '#collapsed' => $collapsed,
  );

  $form['sirportly_account']['sirportly_api_token'] = array(
    '#type' => 'textfield',
    '#title' => t('API Token'),
    '#description' => t('Your Sirpotly API Token. See <a href="http://sirportly.com/docs/api-specification">documentation</a> for details.'),
    '#default_value' => variable_get('sirportly_api_token', ''),
    '#required' => TRUE,
  );

  $form['sirportly_account']['sirportly_api_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('API Secret'),
    '#description' => t('Your Sirpotly API Secret. See <a href="http://sirportly.com/docs/api-specification">documentation</a> for details.'),
    '#default_value' => variable_get('sirportly_api_secret', ''),
    '#required' => TRUE,
  );

  // Ticket routing information.

  $form['ticket_information'] = array(
    '#type' => 'fieldset',
    '#title' => 'Department & Brand information',
    '#description' => t('Determine information applied to newly submitted tickets.'),
  );

  $form['ticket_information']['sp_ticket_priority'] = array(
    '#type' => 'select',
    '#options' => variable_get('sirportly_metadata_priorities'),
    '#title' => 'Submitted ticket priority',
    '#required' => TRUE,
    '#default_value' => variable_get('sp_ticket_priority')
  );

  $form['ticket_information']['sp_ticket_status'] = array(
    '#type' => 'select',
    '#options' => variable_get('sirportly_metadata_statuses'),
    '#title' => 'Submitted ticket status',
    '#required' => TRUE,
    '#default_value' => variable_get('sp_ticket_status'),
  );

  $form['ticket_information']['sp_ticket_department'] = array(
    '#type' => 'select',
    '#options' => variable_get('sirportly_metadata_departments'),
    '#title' => 'Submitted ticket department',
    '#description' => t('Select the department this ticket will be assigned to.'),
    '#required' => TRUE,
    '#default_value' => variable_get('sp_ticket_department'),
  );

  // Knowledgebase stuff.

  $form['sp_knowledgebases'] = array(
    '#title' => t('knowledgebases'),
    '#description' => t('Make your Sirportly knowledgebases visible in the support section.'),
    '#type' => 'fieldset',
  );

  $form['sp_knowledgebases']['sp_active_knowledgebase'] = array(
    '#type' => 'checkboxes',
    '#options' => variable_get('sirportly_metadata_knowledgebases', array()),
    '#title' => t('Active knowledgebases'),
    '#description' => t('Active knowledgebases will be visible to site users'),
    '#default_value' => variable_get('sp_active_knowledgebase'),
  );

  // Styling.

  $form['sp_styling'] = array(
    '#title' => t('Default Styles'),
    '#type' => 'fieldset',
  );

  $form['sp_styling']['sp_enable_styling'] = array(
    '#type' => 'checkbox',
    '#title' => t('Include default module styles'),
    '#description' => t('Include defauly sirportly module styles.'),
    '#default_value' => variable_get('sp_enable_styling', 1),
  );


  return system_settings_form($form);

}

/**
 * Determine if all the neccessary settings have been set.
 * @return bool True if all settings are ok, false if not.
 */
function __determine_all_sp_set() {

  $token = variable_get('sirportly_api_token', NULL);

  $secret = variable_get('sirportly_api_secret', NULL);

  $status = variable_get('sp_ticket_status', NULL);

  $priority = variable_get('sp_ticket_priority', NULL);

  $department = variable_get('sp_ticket_department', NULL);

  $test = (is_string($token) && is_string($secret)) && $status && $priority && $department ? TRUE : FALSE;

  if (!$test) {
    drupal_set_message(t('Not all of the required credentials have been set in order to use the Sirportly module, please <a href="">configure</a> then now.'), 'error');
  }

}

/**
 * Menu callback to allow you to submit a ticket to sirportly.
 * @return string Content for the page.
 */
function sirportly_ticket_submit() {

  __determine_all_sp_set();

  $token = variable_get('sirportly_api_token', '');

  $secret = variable_get('sirportly_api_secret', '');

  $status = variable_get('sp_ticket_status', '');

  $priority = variable_get('sp_ticket_priority');

  $department = variable_get('sp_ticket_department');

  $company_name = variable_get('company_name', 'us');

  $output = '<p>Need help with something? Fill out the form below and a support request will be sent directly to ' . $company_name . '.';

  $output .= render(drupal_get_form('sirportly_ticket_submit_form'));

  return $output;

}

/**
 * DFAPI Form for the submit page.
 * @return array Form content.
 */
function sirportly_ticket_submit_form() {

  global $user;

  $form['sirportly_name'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => 'Your name',
  );
  $form['sirportly_email'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => 'Your email',
    '#description' => t('Defaults to your site email address, but please feel free to provide any.'),
    '#default_value' => $user->mail,
  );
  $form['sirportly_subject'] = array(
    '#type' => 'textfield',
    '#maxlength' => 120,
    '#title' => t('Subject'),
    '#description' => t("Sum up your issue in a few words."),
    '#required' => TRUE,
  );
  $form['sirportly_message'] = array(
    '#type' => 'textarea',
    '#title' => 'Message',
    '#attributes' => array(
      'style' => 'width:50%;'
    ),
    '#required' => TRUE,
    '#description' => t('Give a more detailed explanation of your problem.'),
  );
  $form['sirportly_submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  $form['#validate'] = array(
    'sirportly_ticket_submit_form_validate'
  );
  $form['#submit'] = array(
    'sirportly_ticket_submit_form_submit'
  );
  return $form;

}

/**
 * Implementation of hook_form_validate()
 */
function sirportly_ticket_submit_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['sirportly_email'])) {
    form_set_error('sirportly_email', "Please enter a valid email address.");
  }
}

/**
 * Implementation of hook_form_submit()
 */
function sirportly_ticket_submit_form_submit($form, &$form_state) {

  $token = variable_get('sirportly_api_token', '');

  $secret = variable_get('sirportly_api_secret', '');

  $status = variable_get('sp_ticket_status', '');

  $priority = variable_get('sp_ticket_priority');

  $department = variable_get('sp_ticket_department');

  $s = new Sirportly($token, $secret);

  $ticket = array(
    'department' => $department,
    'status' => $status,
    'priority' => $priority,
    'subject' => $form_state['values']['sirportly_subject'],
    'name' => $form_state['values']['sirportly_name'],
    'email' => $form_state['values']['sirportly_email'],
  );

  // Create the ticket.
  $create_ticket = $s->create_ticket($ticket);

  // if a reference is received in return, post the message and subject as an update, otherwise, throw an error.
  if (isset($create_ticket['reference'])) {

    $customer_id = $create_ticket['customer']['id'];

    $update = $s->post_update(
      array(
        'ticket' => $create_ticket['reference'],
        'message' => $form_state['values']['sirportly_message'],
        'subject' => $form_state['values']['sirportly_subject'],
        'customer' => $create_ticket['customer']['id'],
      )
    );

    if (isset($update['id'])) {

      drupal_set_message(t("Thanks, your ticket was received successfully."));

      global $user;

      $list_key = "Sirportly_ID_list_{$user->uid}";

      $customer_list = variable_get($list_key, NULL);

      $customer_list[$customer_id] = $customer_id;

      variable_set($list_key, $customer_list);

      drupal_goto('admin/sirportly');
    }
    else {
        form_set_error("", "Your ticket could not be submitted due to an unknown error, please try again in 30 seconds.");
    }

  }
  else {

    // Ticket was not created, throw error.
    form_set_error("", "Your ticket could not be submitted due to an unknown error, please try again in 30 seconds.");
  }

}

/**
 * Get and cache the data from sirportly for things like priorities, statuses etc.
 */
function cache_sirportly_metadata() {

  $token = variable_get('sirportly_api_token', '');

  $secret = variable_get('sirportly_api_secret', '');

  $s = new Sirportly($token, $secret);

  $kbs = variable_get('sirportly_metadata_knowledgebases', NULL);

  if (!$kbs) {

    $kb_list = array();

    $kbs = $s->kb_list();

    foreach ($kbs as $kb) {
      $kb_list[$kb['id'] . ':' . $kb['name']] = $kb['name'];
    }

    variable_set('sirportly_metadata_knowledgebases', $kb_list);

  }

  $statuses = variable_get('sirportly_metadata_statuses', NULL);

  if (!$statuses) {
    $status_data = $s->statuses();
    $status_array = array();
    foreach ($status_data as $status) {
      $status_array[$status['id']] = $status['name'];
    }
    variable_set('sirportly_metadata_statuses', $status_array);
  }

  $priorities = variable_get('sirportly_metadata_priorities', NULL);

  if (!$priorities) {
    $priority_data = $s->priorities();
    $p_array = array();
    foreach ($priority_data as $priority) {
      $p_array[$priority['id']] = $priority['name'];
    }
    variable_set('sirportly_metadata_priorities', $p_array);
  }

  $departments = variable_get('sirportly_metadata_departments', NULL);

  if (!$departments) {
    $brands = $s->brands();
    $department_list = array();
    foreach ($brands as $brand) {
      foreach ($brand['departments'] as $department) {
        $department_list[$department['id']] = $department['name'] . ' ('.$brand['name'].')';
      }
    }
    variable_set('sirportly_metadata_departments', $department_list);
  }
}

function sirportly_kb_view($kb_id) {

  $token = variable_get('sirportly_api_token', '');

  $secret = variable_get('sirportly_api_secret', '');

  $s = new Sirportly($token, $secret);

  $kb = $s->kb($kb_id);

  if (isset($_GET['p']) && is_string($_GET['p'])) {
    $kbp = $s->kb_page($kb_id, $_GET['p']);
  }
  else {
    $kbp = $s->kb_page($kb_id, '');
  }
  drupal_set_title($kbp['page']['title']);
  $menu = sp_recurseMenuItems($kb);

  return theme('knowledgebase_page', array(
    'menu' => $menu,
    'content' => Markdown($kbp['page']['content']),
  ));
}

function sp_recurseMenuItems($menu, $link_base = NULL) {

  $output = '<ul>';

  foreach ($menu as $m) {

    $output .= '<li>';

    if (!isset($link_base) && !$m['full_permalink']) {
      $output .= l($m['title'], 'admin/sirportly/knowledge/view/'.arg(4));
    }
    else {
      $output .= l($m['title'], 'admin/sirportly/knowledge/view/'.arg(4), array('query' => array('p' => (isset($link_base) ? $link_base.'/' : '') . $m['full_permalink'])));
    }

    if (isset($m['children'])) {
          $output .= sp_recurseMenuItems($m['children'], $m['permalink']);
    }

    $output .= '</li>';

  }

  $output .= '</ul>';

  return $output;

}

/**
 * Lovely dump function.
 * @param  mixed $var any type of variable to dump
 */
function dump($var) {
  echo '<pre>'.print_r($var,1).'</pre>';
}

/**
 * Implementation of hook_flush_caches();
 * Does not actually return any table names, but uses the invocation to clear the variables we don't want any more out.
 */
function sirportly_flush_caches() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'sirportly_metadata%'");
  return array();
}